name: Deploy new App Service

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: "rg-user05"
        required: true
        type: string
jobs:
  add-resource:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ github.event.inputs.resourceGroup }}
          template: ./templates/app-service.json
          parameters: ./templates/app-service.parameters.json